MySQL DB Schema.sql
app/application/views/layouts/login.php
app/application/views/project/sidebar.php
web.config

Fix error in the sidebar view
Fix the issue of not showing the logo on the login page
add IIS configuration to support URL rewrite

Bug Fix & Minor updates 

---

install/update_v1-5_6.sql

This update will act on all tables which act agains the tags.
- Insert a new tag id=9 tab= status:in Progress
- recalculate all tag's id  in tabs table
- recalculate all id_tag in issues table

Update the database

---

app/application/models/project/issue/comment.php

Please try it before i'll merge it to master branch.

You now can change your tags on every comment

---

app/application/language/en/tinyissue.php
app/application/language/fr/tinyissue.php
app/application/models/project/issue.php
app/application/views/project/index/issues.php
app/assets/css/app.css

Inscription during new issue creation, color bar while commenting.

Duration max for an issue

---

app/application/language/es/tinyissue.php

I hope to be able to do whatever we all want to be done soon without touching the translation files anymore.

Spanish translation

---

app/application/views/project/index/issues.php

Testing and fixing period for both percentage and duration colored progress bars.

Bug correction for 0% and 0 day work done on issues list

---

app/application/language/es/tinyissue.php

Watch your tinyissue.php translation file, 
make sure this counts the two last line :  
with a comma at the end of preceding line like:
'fileupload_button' => 'file upload',
'countdown' => 'countdown',
'duration' => 'duration'

Missing comma in file, everything turned wrong from that. --- fixed.

---

app/application/controllers/roles.php
app/application/language/en/tinyissue.php
app/application/language/es/tinyissue.php
app/application/language/fr/tinyissue.php
app/application/routes.php
app/application/views/layouts/blocks/footer.php
app/application/views/layouts/blocks/header.php
app/application/views/layouts/login.php
app/application/views/roles/index.php
app/application/views/tags/index.php

New function in administration section: customize your « role » descriptions

Now you can personalize your user s   roles

---

app/application/views/user/issues.php

Even on user issues view ... progress bar and duration bar

---

README.md
app/laravel/lang.php

Only let people know that the project is still on its way to be better and better;
Removing some programming bookmark set it even nicer.

Little changes

---

app/application/language/all.php
app/application/views/layouts/login.php

Almost everything will be vewable in your own language.
The app/application/language/all.php file has been added here, make sure your language appears in.

Translations for login window

---

MySQL DB Schema.sql
app/application/controllers/project.php
app/application/language/en/tinyissue.php
app/application/language/es/tinyissue.php
app/application/language/fr/tinyissue.php
app/application/models/project.php
app/application/views/project/edit.php
app/application/views/project/sidebar.php
install/mysql-structure.php
install/update_v1-5_6.sql

Be carefull, you may need to update your database, using this version.
See the "install/update_v1-5_6.sql" file to do your database update.

Links to your web sites

---

app/application/views/project/edit.php
app/application/views/project/sidebar.php

If there no link associated to you project ( link to development web page, link git deposit or link to production webpage), the entire links section is hidden from sidebar

Final touch on sidebar

---

app/application/views/project/issue/index.php

Little change on line 32 of app/application /views/project/issue/index.php

Duration not set OR equal 0

---

app/application/controllers/project/issue.php
app/application/language/fr/email.php
app/application/models/project/issue.php
app/application/views/layouts/blocks/header.php
app/application/views/project/issue/activity/reassign-issue.php
app/application/views/project/issue/index.php

When someone reassign ticket to another user, right on the page of this very issue, the new assignee will receive an email, and the this very page where the issue is shown will show the new assignation.  All this did theoricaly exist, but didn't work.  It now works.  All this was done through a pup-up, it is now done through an iframe.  That means there's no more « flash » in your face.

Bugs now sends email when someone reassign thy issue

---

MySQL_DB_Schema.sql

Please note:  the name has been changed, now including undescores instead of spaces.

MySQL DB update after very long while.

---

app/application/views/administration/index.php
install/update_v1-6_0.sql
install/updates_status.txt
updates_status.txt

We will now work with branches according to the following rules:
- New functions, new options => release_nextNumberRelease branch
- Updates for PHP, CSS, JS ou which ever language according to this language update => specific name
- master:  running and actual version, actual release.
Thanks

Working on next release which will include auto-update

---

app/application/controllers/project/issue.php
app/application/views/activity/retag-issue.php
app/application/views/project/issue/index.php

I know why, rapid-tagging has been lost for few commits.

Back to running rapid-tag

---

app/application/language/en/tinyissue.php
app/application/language/fr/tinyissue.php
app/application/models/project/issue.php
app/application/views/project/issue/edit.php
app/application/views/project/issue/new.php

As said in title: Bugs permits ticket's duration change both when you create a new issue or edit it.

No permits to change ticket's duration

---

app/application/views/activity/attached-file.php
app/laravel/core.php
app/laravel/error.php
app/laravel/redirect.php
app/laravel/section.php
app/laravel/vendor/Symfony/Component/HttpFoundation/File/MimeType/FileBinaryMimeTypeGuesser.php
app/laravel/view.php

Sorry for that, i should do that into a new branch.
That's why I bring it back to original.  
Then, I'll start new branch without any ob_ code in.

Tests about ob_

---

app/application/controllers/projects.php

Works with root and absolute path instead of relative path while installing the reports components

Correction au calcul des sous-répetoires

---

app/laravel/auth/drivers/driver.php
app/laravel/crypterSSL.php

Some misstyping have been changed.
Still ... for those who did work with php7.0 or older the password encryption doesn't work.
Let see if it works with a brand new project all done in php 7.2

One step further : correction in two files

---

app/application/libraries/mail.php

Small fix for the Mail sending code

---

app/application/libraries/mail.php
app/application/models/project/issue.php
app/application/models/project/issue/comment.php
app/application/models/user.php
app/application/views/project/issue/index.php
config.app.example.php

Back to a centralized function for mailing.
This time, it works good with 'mail' as value in your config.app.php 
I set this value as default.  No time - for now - to work on stmp, pop3 or google methods.
Anyways, mail value permits to send both plain text and html
Please refer to file   config.app.example.php   also uptaded here for default values

Mailing now works good with method = mail in config.app.php

---

app/application/views/project/issue/index.php
app/assets/css/app.css

Same modification as Nydareld but in CSS version

z-index for dropdowns

---

app/application/views/project/issue/new.php
app/vendor/ckeditor/Bugs_code/showeditor.js

Did work with ckeditor.  It now does.

Editeur WYSIWYG en issue new.php

---

README.md
app/application/language/fr/tinyissue.php
app/application/views/layouts/blocks/default_sidebar.php
app/application/views/project/sidebar.php

Sidebar's elements indicate the number of active tickets.
If this number is positive, click on the item will lead to the active tickets list.
If this number is null, click on the item will lead to the « activities » tab.
The same behavior is not offered by the drop list in the sidebar.

Quicker links in the sidebar

---

app/application/config/tinyissue.php

No big changes, but only adjustment for updating.

Version 1.6 release 1c

---

app/application/controllers/project/issue.php
app/application/views/activity/attached-file.php
app/application/views/project/issue/activity/attached-file.php
app/application/views/project/issue/index.php

Priority status visible when the issue is shown with all its comments, in such situation - also - the issue title is bigger.

Priority more visible

---

README.md

Note about the PHP version requiered

README infos updated.

---

README.md

We do not support PHP 5.x anymore

PHP requierement updated

---

app/application/config/tinyissue.php
app/application/language/en/tinyissue.php
app/application/language/fr/tinyissue.php
app/application/libraries/checkVersion.php
app/application/views/administration/index.php

BUGS checks first if the system is online before it tries to compare versions.

Version 1.7 - revision 1b

---

.gitignore
app/application/config/tinyissue.php
app/application/views/project/issue/index.php
app/application/views/projects/reports.php
app/assets/css/app.css

Un retour de plus au bas des pages views issue index
Une couleur moins agressante à l'oeil pour les rapports personnalisés.

Améliorations visuelles

---

app/application/config/tinyissue.php
app/application/language/en/tinyissue.php
app/application/language/fr/tinyissue.php
app/application/views/layouts/blocks/default_sidebar.php
app/application/views/project/sidebar.php
app/assets/css/app.css
app/vendor/searchEngine/Chercher.php
app/vendor/searchEngine/index.php
app/vendor/searchEngine/tools.php

Two new features :   
- responsive template
- search tool to find back some expression from project name, issu title or issue content.

Responsive + search tool

---

app/application/config/tinyissue.php
app/application/language/en/tinyissue.php
app/application/language/fr/tinyissue.php
app/application/views/layouts/blocks/default_sidebar.php
app/application/views/project/sidebar.php
app/assets/css/app.css
app/vendor/searchEngine/index.php

This is the first release of BUGS with responsivness capabilities.
Please feel free to comment this release.  We're waiting for such comments to launch the responsive version under the "stable" branch.
This release has no more reference to any kind of "magic_quote" which is deprecated since PHP 7.0 (but still tolerated under 7.0, 7.1, 7.2, 7.3), getting reading for new generation of PHP.
Totaly new tool, integrated to the sidebar: search tool which search into projects name and description, issues titles and comments.

Search tool, and responsive template

---

app/application/config/tinyissue.php
app/application/controllers/project/issue.php
app/application/models/project/issue/comment.php
app/application/views/activity/attached-file.php
app/application/views/project/issue/activity/attached-file.php
app/application/views/project/issue/index.php
app/application/views/project/issue/new.php
app/assets/js/project.js
app/vendor/Trumbowyg/Bugs_code/showeditor.js
app/vendor/ckeditor/Bugs_code/showeditor.js

SInce very long, no one did let me know that ckeditor did not let edit an old comment.
It is now possible.
You can now attach a file ( any kind ) to a new issue.

Ability to edit comment AND ability to attach file on new issue

---

app/application/config/tinyissue.php

Reports reserved to admin and managers only ---  …release number

---

app/application/controllers/ajax/ListMbr.php
app/application/controllers/ajax/db.php
app/application/controllers/project/issue.php
app/application/language/en/tinyissue.php
app/application/language/fr/tinyissue.php
app/application/models/role/permission.php
app/application/routes.php
app/application/views/project/issue/edit.php
app/application/views/project/sidebar.php
app/assets/css/app.css
app/assets/js/app.js
app/assets/js/project.js

Change ticket from project A to project B.
When you change a ticket, the system asks you to assign the ticket to one of project B's members.
Works great on test bench.

Changer un billet de projet: complet

---

app/application/controllers/ajax/ProjectAddMbr.php
app/application/controllers/ajax/ProjectAddMbrListe.php
app/application/language/en/tinyissue.php
app/application/language/fr/tinyissue.php
app/application/views/project/edit.php
app/application/views/project/sidebar.php
app/assets/css/app.css
app/assets/js/app.js
app/assets/js/project.js

Both methods are good: 
- from sidebar
- from project edit page.

Add/remove user to/from project

---

app/application/config/tinyissue.php
app/application/views/project/index.php
app/application/views/project/issue/new.php

This change is applied only on "New ticket" button and views/issue/new   
If you find other(s) way(s) to get into new ticket creation available for level 1, please let me know.

New ticket no more available to Level 1 ( observer ) 

---

app/application/views/project/edit.php
app/application/views/project/index.php
app/application/views/project/issue/activity/ChangeIssue-project.php
app/application/views/project/issue/activity/attached-file.php
app/application/views/project/issue/activity/close-issue.php
app/application/views/project/issue/activity/comment.php
app/application/views/project/issue/activity/reassign-issue.php
app/application/views/project/issue/activity/reopen-issue.php
app/application/views/project/issue/activity/update-issue-tags.php
app/application/views/project/issue/edit.php
app/application/views/project/issue/index.php
app/application/views/project/issue/new.php

Better control on acces to issues and projects.

Acces contrôlé aux projets et billets, selon aux droits de chq usager

---

app/vendor/searchEngine/Chercher.php

Recherche améliorée, mieux ciblée.
Enhenced search tool.

Recherche de bilet accessible à tous

---

app/application/controllers/ajax/todo.php
app/application/models/project/issue/comment.php
app/application/views/project/issue/new.php

Testés:
En lecteur
- commenter un billet
En admin
- ajout d'un billet
- commentaire à un billet
- modifier un billet
- changer le pourcentage de progression
- ajouter et ôter des étiquettes

Là ce semble bon

---

app/application/controllers/project/issue.php
app/application/views/project/issue/index.php

modif dans ctrls project issue issue.php

Espérant avoir résolu le problème de courriel, 

---

app/application/controllers/project/issue.php
app/application/models/project/issue/comment.php
app/application/views/project/issue/index.php

Owner can change the status of a ticket when he comments the ticket

---

app/application/config/tinyissue.php
app/application/views/administration/update/index.php

Without this correction, update the entire BUGS will block.

correctif pour les usager de update_en.php

---

app/application/views/layouts/blocks/default_sidebar.php

Icon src is now based on complete URL ( static )  instead of relative.
Subscript call also is based on complete URL instead of relative.

icon problem solved in the sidebar

---

app/application/controllers/project/issue.php
app/application/libraries/fpdf/makefont/makefont.php
app/application/models/project/issue.php
app/application/views/project/issue/activity/close-issue.php
app/application/views/project/issue/index.php
app/assets/css/app.css

Many little changes, but the most obvious is the position (center / center ) of the notices.

Notice smaller and centered

---

app/application/controllers/ajax/SendMail.php
app/application/libraries/mail.php
app/application/models/user.php
app/application/views/administration/index.php

Je n'ai pas réparé l'envoi du courriel lors de la création d'un nouvel usager, mais simplement permis que ça ne bloque plus.
J'y reviendrai plus tard.

En attendant

---

app/application/config/tinyissue.php
app/application/controllers/ajax/SendMail.php
app/application/models/project/issue/comment.php
app/assets/js/admin.js

Voici la première version fonctionnelle des textes personalisés intégrés aux courriels.

Texte personnalisé intégré aux courriels

---

app/application/controllers/ajax/ChgConfEmail.php
app/application/views/administration/index.php

Les champs intro et bye peuvent avoir besoin de slashes pour l'affichage, mais il faut les enlever lors de l'enregistrement.  Tout ça se fait par les présents changements.

Ajout et retrait de slashes pour permettre l'affichage

---

app/application/config/tinyissue.php
app/application/controllers/ajax/SendMail.php
app/application/libraries/PHPmailer/class.phpmailer.php
app/application/views/administration/index.php

Il y avait des erreurs dans SendMail, mais aussi dans le code de PHPmailer

PHPmailer, smtp et autres modes fonctionnels

---

app/application/config/tinyissue.php
app/application/controllers/ajax/SendMail.php
app/laravel/crypterSSL.php

Remplacement de toutes les fonctions de comparaisons ?? par des vérifications isset dans SendMail

Sans la fonction très utile ??

---

app/application/config/tinyissue.php
app/application/controllers/ajax/SendMail.php
app/vendor/ckeditor/config.js

Utilisation limitée des images à celles du web seulement et meilleure  correction des variables

Seules images: web; meilleure correction des variables

---

app/application/config/tinyissue.php
app/application/controllers/ajax/SendMail.php
app/application/controllers/project/issue.php
app/application/views/activity/update-issue-tags.php
app/application/views/project/issue/activity/update-issue-tags.php
app/application/views/tags/new.php
install/MySQL_DB_Schema.sql

Nous revenons à une version fonctionnelle afin de gérer les couleurs d'étiquettes de manière à ce que les mises à jour soient prises en considération.
Veuillez préférer ici le chargement d'une compaction complète du dépôt (relase) au seul chargement des fichiers modifiés.

Retour en arrière - ver 1.8 révision r

---

app/application/controllers/ajax/SendMail.php
app/application/language/en/tinyissue.php
app/application/views/activity/dashboard.php

Les messages personnalisés qui incluent une référence au nom du projet voient désormais ce nom entre guillemets et sans lien URL dans le titre

De meilleurs titres aux messages

---

app/application/controllers/project/issue.php
app/application/views/project/issue/index.php

Dommage, l'émission de courriel - lors d'un ajout ou de retrait d'étiquette - doit être temporairement mise côté.
Nous y reviendrons.

Retour aux étiquettes affichées

---

app/application/controllers/project.php
app/application/models/project.php
app/application/views/projects/index.php

Suppression et ajout d'un projet fonctionnels.

Gestion améliorée des projets

---

app/application/config/tinyissue.php
app/application/controllers/ajax/ChgPrefGen.php
app/application/controllers/project/issue.php
app/application/models/project/issue/comment.php
app/application/views/administration/users/add.php
app/application/views/administration/users/edit.php
app/application/views/project/index/issues.php
app/application/views/project/issue/activity/comment.php
app/application/views/project/issue/index.php

Plusieurs petits soucis réglés: 
- édition de commentaires longs
- suppression d'un commentaire
- liste des langues dans la définition ou l'édition d'un usager

Édition correcte des commentaires longs ou brefs

---

app/application/controllers/ajax/ChgPrefGen.php
app/application/controllers/ajax/SendMail.php
app/application/language/en/install.php
app/application/language/fr/install.php
app/application/views/administration/index.php
app/application/views/project/edit.php
app/application/views/project/issue/index.php
app/assets/js/admin.js
config.app.example.php
install/MySQL_DB_Schema.sql
install/update_v1-8_7a.sql
install/update_v1-8_7s.sql

Vérification de l'état du seveur courriel avant d'envoyer un message
Vérfication de l'existance d'un élément tableau avant de l'appeler.

Petites corrections

---

.gitignore
app/application/config/tinyissue.php
app/application/controllers/ajax/SendMail.php
app/application/controllers/projects.php
app/application/language/en/tinyissue.php
app/application/language/fr/tinyissue.php
app/application/models/project.php
app/application/views/projects/new.php
app/assets/js/project-new.js
install/update_v1-8_7u.sql

Les droits de gestion, modification, édition ou visualisation sont mal gérés par BUGS.
Nous entrons ici dans la première étape de correctifs à cette faille.
En première étape, vous trouverez un fichier SQL qui rendra utile la table projects_users qui  a jusqu'à maintenant été négligée.
Nouvelle fonctionnalité: vous déterminez le rôle des usagers lors de la création d'un nouveau projet.
Les présents correctifs touchent aussi à un bug ou deux rencontrés en chemin.

Gestion des droits aux projets

---

app/application/controllers/ajax/ProjectAddMbr.php
app/application/controllers/ajax/ProjectAddMbrListe.php
app/application/controllers/ajax/project.php
app/application/models/project/user.php
app/application/views/project/edit.php
app/application/views/project/sidebar.php
app/assets/js/app.js

Ceci tient compte du role ( minium 3 ou 4) qu'a l'usager éditant le rôle des autres.

Gestion des rôles fonctionnelle dans édition projet

---

app/application/config/tinyissue.php
app/application/controllers/roles.php
app/application/language/en/tinyissue.php
app/application/language/fr/tinyissue.php
app/application/models/project/user.php
app/application/models/user.php
app/application/views/administration/users/edit.php

NULL could not be shown.  Now it's back

Erreur affichage des roles corrigée

---

app/application/config/tinyissue.php
app/application/views/activity/dashboard.php
app/laravel/asset.php
app/laravel/url.php

Make sure that the template's name starts by uppercase or is Default

Assurer un nom du canevas commençant en majuscule ou est Default

---

app/laravel/asset.php

Correction on top of previous patch.

Nom du canevas commençant en majuscule ou est Default

---

app/application/config/tinyissue.php
app/application/views/layouts/login.php
app/assets/css/login.css

Mise à jour lors de la connexion, de manière automatique ou manuellement.

Update database manually or automatically on login

---

app/application/config/tinyissue.php
app/application/controllers/ajax/administration.php
app/application/models/administration.php
app/application/models/user.php
app/application/views/activity/update-issue-tags.php
app/application/views/administration/index.php
app/application/views/layouts/login.php
app/assets/css/login.css
app/assets/js/admin.js

Auto BDD's update on login
Maaged  BDD's in admin page.
Some others small patches.

Mise à jour de la BDD automatisée en login, commandée en admin

---

app/application/config/tinyissue.php
app/assets/css/Sombre_B/app.css
app/assets/css/Sombre_G/app.css
app/assets/css/Sombre_R/app.css
app/assets/js/app.js

Ajout de nouvel usager a projet de nouveau fonctionnel

Ajout de nouvel usager a projet de nouveau fonctionnel

---

app/application/config/tinyissue.php
app/application/models/administration.php
app/application/views/activity/update-issue-tags.php
app/application/views/administration/users/edit.php
app/application/views/layouts/login.php
app/application/views/todo/index.php
install/update_v1-1_1.sql
install/update_v1-2_9.sql
install/update_v1-3_1.sql
install/update_v1-3_2.sql
install/update_v1-3_3.sql
install/update_v1-8_7p.sql

La mise à jour de la structure BDD est fonctionnelle pour toutes les mises à jour enregistrées depuis 2017.
Aussi, au premier afichage, le bon nombre de billets et listé dans les pages TODO et MesBillets.

Auto update of BDD`s structure

---

app/application/config/tinyissue.php
app/application/controllers/login.php
app/application/models/user.php
app/application/views/layouts/login.php
app/laravel/routing/router.php
app/laravel/session.php
app/laravel/session/payload.php
app/laravel/vendor/Symfony/Component/HttpFoundation/LaravelRequest.php
app/laravel/vendor/Symfony/Component/HttpFoundation/Request.php
app/laravel/vendor/Symfony/Component/HttpFoundation/Response.php
app/laravel/view.php
index.php
install/config-setup.php
install/index.php
install/install.php

La version installée sous Windows 10 avec XAMPP ( PHP 8.0 ) bloquait.
Les améliorations ici apportées nous mènent jusqu'à la connexion à BUGS après une installation en version simplifiée.
Nous resteront les étapes de création de projet, création de billet à vérifier avant la mise en ligne de version stable et publication mondiale.
Les présentes corrections sont inutiles si votre BUGS fonctionne actuellement bien.

Mises à niveau en vue de PHP 8.0

---

app/application/config/tinyissue.php
app/application/controllers/home.php
app/application/models/project/issue.php
app/application/models/user.php
app/application/views/activity/dashboard.php
app/application/views/administration/users/add.php
app/application/views/layouts/blocks/default_sidebar.php
app/assets/css/Default/app.css

Quelques réparations en vue de la vesrion vraiment fonctionnelle.
Some patches on creating new user:  admin may now define a password for this new user.
Creating the really first project and first issue:  the new issue has now a starting date so it shows in « open issues » list.

Quelques réparations

---

app/application/config/tinyissue.php
app/application/controllers/home.php
app/application/models/project/issue.php

Imposons une valeur par défaut au créateur de billet, imposons au créateur du tout premier billet de suivre celui-ci

Correctifs demandés.

---

app/application/config/tinyissue.php
app/application/libraries/mail.php
app/application/views/user/settings.php

Correction apportée aux notices admin à propos des connexions de ses usagers

Connexion usagers améliorée

---

app/application/config/tinyissue.php
install/mysql-structure.php

On me dit que la première table (activities) n'est pas créée au moment de l'installation initiale dans certaines circonstances.  Ce problème ne survient ni avec Debian, ni sous Windows, mais sous une autre version de Linux.  Les fichiers mysql ... .sql et .php ont donc été modifiés en vue de permettre à tous les usagers de bien installer toutes les tables.  De plus, au cours des prochains jours, sera ajoutée une étape de vérification lors de l'installation en vue de s'assurer que toutes les tables soient bien créées et remplies.

Correction aux fichiers install
